### PR TITLE
did some blue color work

### PR DESCRIPTION
**Pull request by ItzNico102**

### CODE REVIEW

**Comment by mikaelssen** [comment]
Earan remasteted this last, but looks ok to me

**Comment by EaranMaleasi** [comment]
@ItzNico102 do you really intend to change the Team blue color whenever anyone writes something.? Because that is going to happen right now. Not just when somebody from team blue writes something.

**Comment by ItzNico102** [comment]
Yup

**Comment by ItzNico102** [comment]
Giess we're ready to merge

**Pull request merged**
